#!/bin/bash
GRUPO=$(pwd)
DEF_EXE_DIR="/bin"
RESERVED="dirconf"
VALID="N"
clear
echo -e "###\tInstalador del sistema EPLAM\t###\n"
echo -e "- Para aceptar las opciones por default (), solamente presione enter.\n"
echo -e "- Todos los directorios deben ser ingresados sin '/' al inicio.\n"
## Request exec directory
while [ $VALID == "N" ]; do
  ## Prompt for exec directory
  read -p "Defina el directorio de ejecutables ($GRUPO$DEF_EXE_DIR): " EXE_DIR
  ## Validate user input
  if [ ! -z "$EXE_DIR" -a "$EXE_DIR" != " " ]; then
    VALID="Y"
    for rname in $RESERVED; do
      if [ $EXE_DIR == $rname ]; then
	echo -e "# El nombre $EXE_DIR se encuentra reservado\n"
	VALID="N"
	break
      fi
    done
    ## If name not reserved
    if [ $VALID == "Y" ]; then
      DEF_EXE_DIR="/$EXE_DIR" 
    fi
  else
    VALID="Y"
  fi
done
VALID="N"
