#!/bin/bash
GRUPO=$(pwd)
DIRCONF="dirconf"
CONF_FILE="$GRUPO/$DIRCONF/Instalep.conf"
# Check if already installed
if [ -f $CONF_FILE ]; then
  clear
  echo -e "###\tEl sistema EPLAM ya se encuentra instalado\t###\n"
  exit 0
fi

# Set directory default values
DIRBIN="bin"
DIRMAE="mae"
DIRREC="nov"
DIROK="ok"
DIRPROC="imp"
DIRINFO="rep"
DIRLOG="log"
DIRNOK="nok"
VALID="N"

# Updates reserved values list
update_reserved() {
  RESERVED="$DIRCONF $DIRBIN $DIRMAE $DIRREC $DIROK $DIRPROC $DIRINFO $DIRLOG $DIRNOK" 
}

# Requests directory path
request_dirpath() {
  update_reserved
  local VALID="N"  
  while [ $VALID == "N" ]; do
    ## Prompt for directory
    read -p "$1" UINPUT 
    ## Validate user input
    if [ ! -z "$UINPUT" -a "$UINPUT" != " " ]; then
      VALID="Y"
      for rname in $RESERVED; do
	if [ $UINPUT == $rname ]; then
	  echo -e "\n# El nombre $UINPUT se encuentra reservado\n" >&2
	  VALID="N"
	  break
	fi
      done
      ## If name not reserved
      if [ $VALID == "Y" ]; then
        echo "$UINPUT"
      fi
    else
      VALID="Y"
      echo "$2"
    fi
  done
}

## Create dir paths
create_dirs() {
  update_reserved
  echo -e "\nCreando Estructuras de directorio . . . .\n"
  for dir in $RESERVED; do
    if [ ! -d "$GRUPO/$dir" ]; then
      mkdir "$GRUPO/$dir"  
    fi
  done
}

## Save configuration variables
save_conf() {
  CONF_FILE="$GRUPO/$DIRCONF/Instalep.conf" 
  echo "GRUPO $GRUPO" >> $CONF_FILE 
  echo "DIRBIN $DIRBIN" >> $CONF_FILE 
  echo "DIRMAE $DIRMAE" >> $CONF_FILE 
  echo "DIRREC $DIRREC" >> $CONF_FILE 
  echo "DIROK $DIROK" >> $CONF_FILE 
  echo "DIRPROC $DIRPROC" >> $CONF_FILE 
  echo "DIRINFO $DIRINFO" >> $CONF_FILE 
  echo "DIRLOG $DIRLOG" >> $CONF_FILE 
  echo "DIRNOK $DIRNOK" >> $CONF_FILE 
}

end_install() {
  ## TODO: Save to log
  exit 0
}

CONTINUE="N"
while [ $CONTINUE != "S" ]; do
  clear
  echo -e "###\tInstalador del sistema EPLAM\t###\n"
  echo -e "- Para aceptar las opciones por default (), solamente presione enter.\n"
  echo -e "- Todos los directorios deben ser ingresados sin '/' al inicio ni al final ( Ej: midir/misubdir ).\n"
  echo -e "- El directorio ingresado sera relativo a: $GRUPO\n\n"
  ## Request exec directory
  DIRBIN=$(request_dirpath "Defina el directorio de Ejecutables ($GRUPO/$DIRBIN): " $DIRBIN)
  ## Request file directory
  DIRMAE=$(request_dirpath "Defina el directorio de Maestros y Tablas ($GRUPO/$DIRMAE): " $DIRMAE)
  ## Request updates directory
  DIRREC=$(request_dirpath "Defina el directorio de Recepcion de Novedades ($GRUPO/$DIRREC): " $DIRREC)
  ## Request accepted files directory
  DIROK=$(request_dirpath "Defina el directorio de Archivos Aceptados ($GRUPO/$DIROK): " $DIROK)
  ## Request processed files directory
  DIRPROC=$(request_dirpath "Defina el directorio de Archivos Procesados ($GRUPO/$DIRPROC): " $DIRPROC)
  ## Request reports directory
  DIRINFO=$(request_dirpath "Defina el directorio de Reportes ($GRUPO/$DIRINFO): " $DIRINFO)
  ## Request log directory
  DIRLOG=$(request_dirpath "Defina el directorio de log ($GRUPO/$DIRLOG): " $DIRLOG)
  ## Request rejected directory
  DIRNOK=$(request_dirpath "Defina el directorio de rechazados ($GRUPO/$DIRNOK): " $DIRNOK)

  ## Request minimum free space required
  VALID="N"
  while [ $VALID != "S" ]; do
    DATASIZE=100
    echo -e "\n"
    read -p "Defina espacio minimo libre para la recepcion de archivos en Mbytes ($DATASIZE): " DATASIZE

    ## Check available size
    AVAILABLE_SIZE=$(df -m --output='avail' . | tail -n 1)

    if [ $AVAILABLE_SIZE -lt $DATASIZE ]; then
      echo -e "Insuficiente espacio en disco." 
      echo -e "Espacio disponible: $AVAILABLE_SIZE Mb."
      echo -e "Espacio requerido: $DATASIZE Mb."
      read -p "Intentelo nuevamente." DUMMY_VAR
    else
      VALID="S"
      echo -e "Suficiente espacio en disco."
      echo -e "Espacio disponible: $AVAILABLE_SIZE Mb."
      echo -e "Espacio requerido: $DATASIZE Mb."
      read -p "De enter para continuar." DUMMY_VAR
    fi
  done

  clear
  ## Show configured directories
  echo -e "\nDirectorio de Configuracion: $GRUPO/$DIRCONF"
  echo -e "Directorio de Ejecutables: $GRUPO/$DIRBIN"
  echo -e "Directorio de Maestros y Tablas: $GRUPO/$DIRMAE"
  echo -e "Directorio de Recepcion de Novedades: $GRUPO/$DIRREC"
  echo -e "Directorio de Archivos Aceptados: $GRUPO/$DIROK"
  echo -e "Directorio de Archivos Procesados: $GRUPO/$DIRPROC"
  echo -e "Directorio de Archivos de Reportes: $GRUPO/$DIRINFO"
  echo -e "Directorio de Archivos de Log: $GRUPO/$DIRLOG"
  echo -e "Directorio de Archivos de Rechazados: $GRUPO/$DIRNOK"
  echo -e "Estado de la instalacion: LISTA"

  echo -e "\n"
  read -p "Desea continuar con la instalacion? ( S / N ): " CONTINUE
  ## Catch empty response as 'S'
  if [ -z "$CONTINUE" -o "$CONTINUE" == " " ]; then
    CONTINUE="S"
  fi
done

  read -p "Iniciando Instalacion. Esta Ud. seguro? ( S / N ): " CONTINUE
  ## Catch empty response as 'S'
  if [ -z "$CONTINUE" -o "$CONTINUE" == " " ]; then
    CONTINUE="S"
  fi

  if [ $CONTINUE != "S" ]; then
    end_install
  fi
  
  ## Create directories
  create_dirs

  ## Save config. variables
  save_conf
